name: actions-ci-cd-spring-boot-app

on:
  workflow_dispatch:

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '11' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.node-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Compile
        run: mvn compile
      - name: Build Package
        run: mvn clean package
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: deploy_dist
          path: target/*.jar
  cd:
    needs: ci
    name: Continuous Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create folder
        run: mkdir ~/deploy_dist
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: deploy_dist
          path: deploy_dist
      - name: Copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          strip_components: 1
          source: deploy_dist/*
          target: ${{ secrets.PATH }}
      - name: +x files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            chmod +x ${{ secrets.PATH }}/*
            ${{ secrets.RESTART }}